### ISSUE TITLE
site only loading does not show content

### ISSUE THREAD

**Issue by harshmangalam** [mhatvan/markushatvan.com#15]

**Comment by mhatvan** [comment]
Hey @harshmangalam, thank you for reporting this!
I tested it on Chrome and Firefox and it works fine, what browser are you using?

**Comment by harshmangalam** [comment]
I am using Abrowser based on spidermonkey mozilla on trisquel linux (ubuntu 18.04). when i open it load and automatically refresh infinitely and  no content loaded .

**Comment by mhatvan** [comment]
Hmm, I can't test every smaller browser that there is. Additionally, it is probably a SvelteKit issue.

**Comment by stilet** [comment]
Firefox on Ubuntu 21.04 not show content
