### ISSUE TITLE
Navigating to the blog directly causes an infinite loop of the site reloading

### ISSUE THREAD

**Issue by AdamManuel-dev** [mhatvan/markushatvan.com#17]
If you access the site's blog directly through [this link](https://markushatvan.com/blog/) instead of the [base url](https://markushatvan.com/) it seems to get stuck in a loop loading the page and redirecting to the same URL causing it to re-render, redirect, and repeat infinitely. 

You also have the link to your blog in the README of this repo pointed at the same URL causing the same reload bug.

**Comment by mhatvan** [comment]
Wow, that is one mean bug!! Thanks for reporting this.

No clue where it comes from and why its only the one URL. I will open an issue in SvelteKit to investigate further.

**Comment by mhatvan** [comment]
Closed via https://github.com/mhatvan/markushatvan.com/commit/424ca3452a364562e4b01d07ea7efd003a5d05be
